
logging:
  level:
    ROOT: DEBUG
    com.google.refine: DEBUG

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: .h2.server.properties
    livereload:
      enabled: true
  jackson:
    serialization:
      indent-output: true
#  datasource:
##    type: com.zaxxer.hikari.HikariDataSource
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:file:~/Repo_OpenRefine/refine-data/h2db/db/openrefine;DB_CLOSE_DELAY=-1
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#      path: /h2

server:
  port: 8080
